zjweu:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.76.200.119
    port: 3306
    database: TrainingSystem
    username: Vinca
    password: Ecs@123
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: 127.0.0.1
    port: 6379
    password: '123456'
    database: 10
